### ISSUE TITLE
fatal error: signalDecoder.h: No such file or directory

### ISSUE THREAD

**Issue by mwolter805** [juanboro/esphome-rtl_433-decoder#1]
Hello,
Interested in using your external component to receive 433 sensors and running into the compilation error:
```
In file included from src/esphome/components/rtl_433/rtl_433.cpp:3:
src/esphome/components/rtl_433/rtl_433.h:8:10: fatal error: signalDecoder.h: No such file or directory

***********************************************************************
* Looking for signalDecoder.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:signalDecoder.h"
* Web  > https://registry.platformio.org/search?q=header:signalDecoder.h
*
***********************************************************************

 #include <signalDecoder.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pioenvs/test-s3-t-eth-lite/src/esphome/components/web_server_base/web_server_base.o
*** [.pioenvs/test-s3-t-eth-lite/src/esphome/components/rtl_433/rtl_433.o] Error 1
```

Appears the necessary files are located in https://github.com/juanboro/rtl_433_Decoder_ESP but not sure how to include them. Can you provide direction?

Thank you

**Comment by juanboro** [comment]
I *think* I messed up something in the yaml files in that directory when I was refactoring some things (this is still quite a WIP --- and I'm right now catching up on the ESP-IDF changes with the RMT library)...  

I'll take a look at fixing the example files at some point (next couple weeks I may be pretty busy with winter vacation :-)).

As a WA -- you could try to include something like this which I from my dev env (adapt the paths):
```yaml
esphome:
  name: esp32-dev
  friendly_name: DEV --- override this
  
  platformio_options:
    lib_ldf_mode: "deep+" # only necessary for arduino platform and radiolib arduino SPI dependency

  libraries:
    - RadioLib
    - rtl_433_Decoder_ESP=file:///home/jdkrause/github.com/rtl_433_Decoder_ESP/

# enable if needed point to local dev version
external_components:
  - source: 
      type: local
      path: /home/jdkrause/github.com/esphome-radiolib-cc1101/components
  - source: 
      type: local
      path: /home/jdkrause/github.com/esphome-rtl_433-decoder/components

packages: 
  cc1101_controls: !include /home/jdkrause/github.com/esphome-radiolib-cc1101/cc1101-controls.yaml

```
